config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    omniauth_callbacks: 'callbacks',
    registrations: 'registrations'
  }

  root to: "home#index"
  get "/imprint", to: "home#imprint", as: "imprint"

  resources :rentals, only: :create

  resources :searched_books, only: [:index, :create]

  resources :available_books, only: [:index, :show]

  resources :books, only: [:show] do
    resources :owners, only: [:index, :show]
  end
  resources :borrow_requests, only: :create

  resources :users, only: [:index, :show] do
    resources :rentals, only: [:index, :show, :destroy]
    resources :borrow_requests, only: [:index, :show, :update, :destroy]
    resources :books do
      resources :borrow_requests, only: [:new]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable,
         :omniauth_providers => [:twitter, :github,
                                 :facebook, :google_oauth2]

  has_one :profile
  has_many :book_ownerships
  has_many :books, through: :book_ownerships

  has_many :rentals
  has_many :borrowers, through: :rentals
  has_many :owerns, through: :rentals

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email || email_out_of(auth)
      user.password = Devise.friendly_token[0,20]
    end
  end

  def borrow_requests
    BorrowRequest.where(requester_id: id)
  end

  def lent_requests
    BorrowRequest.where(owner_id: id)
  end

  def name
    "#{first_name} #{last_name}"
  end

  private

  def self.email_out_of(auth)
    "#{auth.info.nickname}@no-mail.com"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  add_breadcrumb "Startseite", :root_path

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end
end

app/views/users/_box.html.haml
= link_to user_path(user) do
  .user-box
    .row
      .col-xs-3.col-sm-2.max-width-80
        = image_tag 'user_dummy.jpg', class: "img-responsive"
      .col-xs-7.col-sm-7
        .row
          .center-block
            %p.user-name
              = user.name
            %p
              =fa_icon "at",class: "emphatized"
              = user.email
      .col-xs-12.col-sm-3.button-group
        - if @book
          = link_to new_user_book_borrow_request_path(user, @book) do
            %button.btn.btn-primary
              Rent now

app/views/users/index.html.haml
.row
  .col-md-8
    - @users.each do |user|
      = render 'users/box', user: user
  .col-md-4
    .google-maps

app/views/users/show.html.haml
%section.profile
  .row
    .col-sm-2.col-xs-12
      = image_tag 'user_dummy.jpg', class: "img-responsive profile-image img-circle"

    .col-sm-10.col-xs-12.profile-info
    %p.lead.emphatized
      = @user.name

%section.section-seperated
  %h3.emphatized
    Bücher der Person
  %hr

  %ul.book-list
    - @user.books.each do |book|
      %li.row.book-box
        .col-sm-2
          .thumbnail
            =image_tag book.image_link
        .col-sm-10
          .book-info
            %h3.title
              =book.title
            %span
              Page Count:
              =book.pages
          .button-group
            = link_to new_user_book_borrow_request_path(@user, @book, requester_id: current_user.id) do
              %button.btn.btn-primary
                = fa_icon 'check'
                Rent