config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    omniauth_callbacks: 'callbacks',
    registrations: 'registrations'
  }

  root to: "home#index"
  get "/imprint", to: "home#imprint", as: "imprint"

  resources :rentals, only: :create

  resources :searched_books, only: [:index, :create]

  resources :available_books, only: [:index, :show]

  resources :books, only: [:show] do
    resources :owners, only: [:index, :show]
  end
  resources :borrow_requests, only: :create

  resources :users, only: [:index, :show] do
    resources :rentals, only: [:index, :show, :destroy]
    resources :borrow_requests, only: [:index, :show, :update, :destroy]
    resources :books do
      resources :borrow_requests, only: [:new]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/imprint.html.haml
.impressum
  %h1
    Impressum
  %br
  %p
    Angaben gemäß § 5 TMG
  %p
    Dennis Hägler
    %br
    Machonstraße 24
    %br
    12105 Berlin
    %br
  %p
    %strong
      Kontakt:
    %br
    Telefon: 017632769237
    %br
    E-Mail: info@bookandread.com
  %p
    %strong
      Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:
    %br
    Dennis Hägler
    %br
    Machonstraße 24
    %br
    12105 Berlin
    %br
  %p
    %br
    %h3
      Haftungsausschluss:
    %br
    %strong
      Haftung für Inhalte
    %br
    %br
    Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und
    Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß
    § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich.
    Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte
    fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit
    hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen
    Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der
    Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen
    werden wir diese Inhalte umgehend entfernen.
    %br
    %br
    %strong
      Haftung für Links
    %br
    %br
    Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben.
    Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten
    Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten
    wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren
    zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten
    ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von
    Rechtsverletzungen werden wir derartige Links umgehend entfernen.
    %br
    %br
    %strong
      Urheberrecht
    %br
    %br
    Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen
    Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der
    Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers.
    Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.
    Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter
    beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine
    Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden
    von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.
    %br
    %br
    %strong
      Datenschutz
    %br
    %br
    Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf
    unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden,
    erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche
    Zustimmung nicht an Dritte weitergegeben. <br>
    Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail)
    Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist
    nicht möglich. <br>
    Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung
    von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich
    widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der
    unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.
    %br
    %br
      Website Impressum erstellt durch
      %a{:href => "http://www.impressum-generator.de"}
        impressum-generator.de
      von
      %a{:href => "http://www.kanzlei-hasselbach.de/rechtsanwaeltin-franziska-hasselbach/"}
        Rechtsanwätin Franziska Hasselbach

app/views/home/index.html.haml
.row
  .col-md-12
    %h1#headline Find your Book
.row.search
  .searchbar-header
    .searchbar
      =form_tag(searched_books_path, class: 'input-group') do
        = text_field_tag :search, params[:search],
          class: 'form-control',
          placeholder: 'Suche nach einem Titel'
        %span.input-group-btn
          =submit_tag('Suchen',
            type: 'submit' ,
            value: 'Suchen',
            class: 'btn btn-primary')
    = link_to 'Alle Ausleihbaren Bücher', available_books_path,
      class: 'available-book-link'

.row.margin-top-100.how-to
  .col-md-4.center-text
    .border
      %h3.bold
        1. Suchen
      .step
        =fa_icon 'search'
      %h4
        Starte die Suche nach einem bestimmten Buch und lass dir anzeigen, wer
        es zuhause hat.
  .col-md-4.center-text
    .border
      %h3.bold
        2. Ausleihen
      .step
        =fa_icon 'comments'
      %h4
        Kontaktiere den örtlich nächsten Freund und einigt euch über Treffpunkt
        und Dauer.
  .col-md-4.center-text
    .border
      %h3.bold
        3. Lesen
      .step
        =fa_icon 'book'
      %h4
        Lies das Buch und lass dich von Book and Read daran erinnern, wann du
        es zurückgeben musst.


%hr

.row.margin-top-100
  .col-md-6
    %h2.info-header
      Das Projekt
    %hr
    %p.welcome-text
      Wir entwickeln ein Portal, das dem Nutzer ein Netzwerk zum Austauschen
      von Fachbüchern bietet. Dieses funktioniert so ähnlich wie ein soziales
      Netzwerk, sodass man einsehen kann, wer welche Bücher besitzt und die
      jeweilige Person sofort kontaktieren kann. So lassen sich auch
      interessante neue Bücher entdecken und den eigenen Freunden Bücher
      empfehlen.
  .col-md-6
    =image_tag("project.jpg", :class => "img-responsive")

.row.margin-top-100
  .col-md-6
    =image_tag("books.jpg", :class => "img-responsive")
  .col-md-6
    %h2.info-header
      Unsere Motivation
    %hr
    %p.welcome-text
      Wir haben festgestellt, dass viele Leute tolle Bücher zuhause haben,
      wovon aber keiner der Mitmenschen etwas weiß. Die eigenen Bücher werden
      meistens zuhause eingelagert und verstauben im Regal, während sich die
      Freunde eventuell die selben Bücher erneut kaufen. Besonders im Bereich
      teurer Fachbücher ist es eine große Hilfe, wenn man sie sich für ein paar
      Wochen einfach von Freunden ausleihen kann.

.row.margin-top-100
  .col-md-6
    %h2.info-header
      Das Team
    %hr
    %p.welcome-text
      Das Team hinter Book and Read besteht aus Martin Görick, Paul Kunze,
      Philip Drozd und Dennis Hägler.
      Wir sind Informatik-Studenten an der Freien Universität Berlin und wir
      entwickeln dieses Portal im Rahmen des
      =link_to("Funpreneur-Wettbewerbs,",
        "http://www.fu-berlin.de/sites/profund/qualifizierung/bachelorstudium/funpreneur-wettbewerb/")
      einer Veranstaltung von Profund Innovation.
  .col-md-6
    =image_tag("team-image.jpg", :class => "img-responsive")