config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    omniauth_callbacks: 'callbacks',
    registrations: 'registrations'
  }

  root to: "home#index"
  get "/imprint", to: "home#imprint", as: "imprint"

  resources :rentals, only: :create

  resources :searched_books, only: [:index, :create]

  resources :available_books, only: [:index, :show]

  resources :books, only: [:show] do
    resources :owners, only: [:index, :show]
  end
  resources :borrow_requests, only: :create

  resources :users, only: [:index, :show] do
    resources :rentals, only: [:index, :show, :destroy]
    resources :borrow_requests, only: [:index, :show, :update, :destroy]
    resources :books do
      resources :borrow_requests, only: [:new]
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors

  has_many :book_ownerships
  has_many :owners, through: :book_ownerships

  has_many :books_authors
  has_many :authors, through: :books_authors

  validates :title, :isbn, presence: true
  validates :isbn, uniqueness: { scope: :isbn_13 }, length: { in: 10..13 }

  def self.search(search)
    where("title like ?", "%#{search}%")
  end

  def self.available
    joins(:book_ownerships).uniq
  end

  def available?
    owners.count > 0
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :assign_user, only: [:index, :create, :destroy]
  before_action :assign_book, only: [:show, :create, :destroy]

  add_breadcrumb "Startseite", :root_path
  add_breadcrumb "Verfügbare Bücher", :available_books_path

  before_action :authenticate_user!

  def index
    @books = @user.books
  end

  def show
    add_breadcrumb "#{@book.title}", :book_path
  end

  def new
    add_breadcrumb "Buch hinzufügen", :new_user_book_path
    @books = Book.all
  end

  def create
    @user.books << @book
    render nothing: true
  end

  def destroy
    @user.books.delete(@book)
    render nothing: true
  end

  private

  def assign_user
    @user = User.find params[:user_id]
  end

  def assign_book
    @book = Book.find params[:id]
  end
end

app/views/books/_book_box.html.haml
=link_to book_path(book) do
  .row.book-box.well.well-sm
    .col-xs-6.col-md-2
      .thumbnail
        =image_tag book.image_link, class: 'book-image'
    .col-md-7
      .row
        %h3.title
          =book.title
      .row
        %span
          Page Count:
        =book.pages
    .col-md-2
      = link_to root_path do
        %button{ class: 'btn btn-primary' }Owner (NOT WORKING)

app/views/books/_box.html.haml
=link_to book_path(book) do
  .row.book-box
    .col-sm-2
      .thumbnail
        =image_tag book.image_link
    .col-sm-10
      .book-info
        %h3.title
          =book.title
        %span
          Anzahl der Besitzer:
          =book.owners.count
      .button-group
        - if book.available?
          = link_to book_owners_path(book) do
            %button.btn.btn-primary
              = fa_icon 'user'
              Zu den Besitzern
        - if current_user
          - unless current_user.books.include? book
            = link_to user_books_path(current_user, id: book),
              method: :post,
              remote: true do
              %button.btn.btn-success
                = fa_icon('plus')
                In eigene Sammlung aufnehmen

app/views/books/index.html.haml
.page-header.container
  %h1
    Bücherliste
    %small
      - if @searched_for
        Gesucht nach:
        %strong
          = @searched_for
  .row
    .col-md-8
      =form_tag(searched_books_path, class: 'input-group') do
        = text_field_tag :search, params[:search],
          class: 'form-control',
          placeholder: 'Buchsuche...'
        %span.input-group-btn
          =submit_tag('Suchen',
            type: 'submit' ,
            value: 'Search',
            class: 'btn btn-primary')
      = link_to 'Alle Ausleihbaren Bücher', available_books_path,
        class: 'available-book-link'
- if @books.empty?
  - if @searched_for
    Leider haben wir kein Buch im System zu:
    %strong
      = @searched_for
  - else
    Bitte gebe ein Buch an.
- else
  - @books.each do |book|
    .row
      .col-md-12
        = render 'books/box', book: book

app/views/books/new.html.haml
.info.alert.alert-warning.margin-top-30
  .row
    .col-sm-1
      .center-text.big-text
        = fa_icon 'lightbulb-o'
    .col-sm-11
      %span
        %h4
          Es existiert noch keine Suche für neue Bücher.
      %span
        %h5
          Bitte nutze
          %strong
            STRG + F
          (Windows), oder
          %strong
            CMD + F
          (Mac), um Bücher zu suchen.

.page-header.container
  %h1
    Füge ein neues Buch hinzu

- @books.each do |book|
  .row
    .col-md-12
      =link_to book_path(book) do
        .row.book-box
          .col-sm-2
            .thumbnail
              =image_tag book.image_link
          .col-sm-10
            .book-info
              %h3.title
                =book.title
              %span
                Page Count:
                =book.pages
              .button-group
                - if current_user
                  = link_to user_books_path(current_user, id: book),
                    method: :post,
                    remote: true do
                    %button.btn.btn-success
                      = fa_icon('plus')
                      Zu meinen Büchern hinzufügen
                - else
                  %button.btn.btn-success.disabled
                    = fa_icon('plus')
                    Add to my Books

app/views/books/show.html.haml
.row.margin-top-10
  .col-sm-4.col-xs-12#book-img
    =image_tag @book.image_link, class:"thumbnail"
  .col-sm-8.col-xs-12
    .panel.panel-primary
      .panel-heading
        %h4
          = @book.title
      .panel-body
        %h5
          .row
            .col-md-3.padding-10
              %strong
                Authors:
            .col-md-9.padding-10
              = @book.authors.join(', ')
          .row
            .col-md-3.padding-10
              %strong
                Pages:
            .col-md-9.padding-10
              = @book.pages
          .row
            .col-md-3.padding-10
              %strong
                Description:
            .col-md-9.padding-10
              = @book.description

%hr

.margin-top-10
  - @book.owners.each do |owner|
    = render 'owners/box', user: owner