config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    omniauth_callbacks: 'callbacks',
    registrations: 'registrations'
  }

  root to: "home#index"
  get "/imprint", to: "home#imprint", as: "imprint"

  resources :rentals, only: :create

  resources :searched_books, only: [:index, :create]

  resources :available_books, only: [:index, :show]

  resources :books, only: [:show] do
    resources :owners, only: [:index, :show]
  end
  resources :borrow_requests, only: :create

  resources :users, only: [:index, :show] do
    resources :rentals, only: [:index, :show, :destroy]
    resources :borrow_requests, only: [:index, :show, :update, :destroy]
    resources :books do
      resources :borrow_requests, only: [:new]
    end
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books
  validates :name, presence: true, uniqueness: true

  has_many :books_authors
  has_many :books, through: :books_authors

  def to_s
    name
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors

  has_many :book_ownerships
  has_many :owners, through: :book_ownerships

  has_many :books_authors
  has_many :authors, through: :books_authors

  validates :title, :isbn, presence: true
  validates :isbn, uniqueness: { scope: :isbn_13 }, length: { in: 10..13 }

  def self.search(search)
    where("title like ?", "%#{search}%")
  end

  def self.available
    joins(:book_ownerships).uniq
  end

  def available?
    owners.count > 0
  end
end

app/models/book_ownership.rb
class BookOwnership < ActiveRecord::Base
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  belongs_to :book

  validates :owner, uniqueness: { scope: :book }
end

app/models/books_author.rb
class BooksAuthor < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

app/models/borrow_request.rb
class BorrowRequest < ActiveRecord::Base
  belongs_to :book
  belongs_to :place

  belongs_to :owner, class_name: User
  belongs_to :requester, class_name: User

  validates_presence_of :owner, :book, :requester, :borrow_start, :borrow_end
  validates :owner, uniqueness: { scope: [:book, :requester] }

  private

  def check_dates
    borrow_start < borrow_end
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :book
  belongs_to :owner, class_name: 'User'
  belongs_to :borrower, class_name: 'User'
  validates :owner, :borrower, :book, :start, presence: true

  def self.from(borrow_request_id)
    borrow_request = BorrowRequest.find(borrow_request_id)
    create(
      book: borrow_request.book,
      owner: borrow_request.owner,
      borrower: borrow_request.requester,
      start: borrow_request.borrow_start,
      end: borrow_request.borrow_end
    )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable,
         :omniauth_providers => [:twitter, :github,
                                 :facebook, :google_oauth2]

  has_one :profile
  has_many :book_ownerships
  has_many :books, through: :book_ownerships

  has_many :rentals
  has_many :borrowers, through: :rentals
  has_many :owerns, through: :rentals

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email || email_out_of(auth)
      user.password = Devise.friendly_token[0,20]
    end
  end

  def borrow_requests
    BorrowRequest.where(requester_id: id)
  end

  def lent_requests
    BorrowRequest.where(owner_id: id)
  end

  def name
    "#{first_name} #{last_name}"
  end

  private

  def self.email_out_of(auth)
    "#{auth.info.nickname}@no-mail.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/available_books_controller.rb
class AvailableBooksController < ApplicationController
  add_breadcrumb "Startseite", :root_path
  add_breadcrumb "Verfügbare Bücher", :available_books_path

  def index
    @books = Book.available
    render 'books/index'
  end

  def show
    add_breadcrumb "Buch", :available_book_path
    @book = Book.find(params[:id])
    render 'books/show'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :assign_user, only: [:index, :create, :destroy]
  before_action :assign_book, only: [:show, :create, :destroy]

  add_breadcrumb "Startseite", :root_path
  add_breadcrumb "Verfügbare Bücher", :available_books_path

  before_action :authenticate_user!

  def index
    @books = @user.books
  end

  def show
    add_breadcrumb "#{@book.title}", :book_path
  end

  def new
    add_breadcrumb "Buch hinzufügen", :new_user_book_path
    @books = Book.all
  end

  def create
    @user.books << @book
    render nothing: true
  end

  def destroy
    @user.books.delete(@book)
    render nothing: true
  end

  private

  def assign_user
    @user = User.find params[:user_id]
  end

  def assign_book
    @book = Book.find params[:id]
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < ApplicationController
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  add_breadcrumb "Startseite", :root_path
  add_breadcrumb "Verfügbare Bücher", :available_books_path
  add_breadcrumb "Buchbesitzer", :book_owners_path

  before_action :authenticate_user!

  def index
    @book = Book.find(params[:book_id])
    @users = @book.owners if @book
  end

  def show
    add_breadcrumb "Details", :book_owner_path
    @user = User.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  after_action :add_name_to_user, only: [:create, :update]

  protected

  def add_name_to_user
    if @user.save
      @user.first_name = user_name[:first_name]
      @user.last_name = user_name[:last_name]
      @user.save
    end
  end

  def user_name
    params.require(:user).permit(:first_name, :last_name)
  end

  def after_sign_up_path_for(resource)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  add_breadcrumb "Startseite", :root_path
  add_breadcrumb "Verleihe", :user_rentals_path

  def index
    @rentals = Rental.where(owner_id: params[:user_id])
  end

  def show
    add_breadcrumb "Aktuell verliehen", :user_rental_path
  end

  def create
    @rental = Rental.from(params[:borrow_request_id])
    if @rental.save
      BorrowRequest.delete(params[:borrow_request_id])
      redirect_to controller: :borrow_requests,
        action: :index,
        user_id: current_user.id,
        notice: 'Rental was successfully created.'
    else
       render :show
    end
  end

  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def user_params
    params.permit(:user_id)
  end
end

app/controllers/searched_books_controller.rb
class SearchedBooksController < ApplicationController
  before_action :set_variables

  add_breadcrumb "Startseite", :root_path
  add_breadcrumb "Verfügbare Bücher", :available_books_path
  add_breadcrumb "Suche"

  def index
    render 'books/index'
  end

  def create
    render 'books/index'
  end

  private

  def set_variables
    @searched_for = search_params[:search]
    @books = Book.search(@searched_for)
  end

  def search_params
    params.permit(:search)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  add_breadcrumb "Startseite", :root_path

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_dropdown.html.haml
.dropdown
  %div#dropdown-login.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
    Hallo
    %strong
      = current_user.first_name
    %span.caret
  %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
    %li
      = link_to 'Meine Bücher', user_books_path(current_user),
        class: 'navbar-link'
    %li
      = link_to 'Meine Anfragen', user_borrow_requests_path(current_user),
        class: 'navbar-link'
    %li
      = link_to 'Meine Verleihe', user_rentals_path(current_user),
        class: 'navbar-link'
    %li
      = link_to 'Edit profile', edit_user_registration_path,
        :class => 'navbar-link'
    %li
      = link_to "Logout", destroy_user_session_path,
        method: :delete,
        :class => 'navbar-link'

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title BookAndRead
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    '//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'logo.png', rel: 'apple-touch-icon', type: 'image/png'
  %body

    .alpha-sign-outer
      .alpha-sign-inner
        %strong
          Dies ist eine Alpha-Version.
        %br
        .small-text
          = link_to 'Was ist eine Alpha-Version?', 'https://de.wikipedia.org/wiki/Entwicklungsstadium_%28Software%29'

    %nav.navbar.navbar-default
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false",
           "data-target" => "#main-navigation", "data-toggle" => "collapse",
            :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'BookAndRead', root_path


        #main-navigation.collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if user_signed_in?
              = render "layouts/dropdown"
            - else
              .dropdown
                =fa_icon "sign-in",class: "navbar-link"
                = link_to "Register", new_user_registration_path,
                  :class => 'navbar-link seperator'
                = link_to "Login", new_user_session_path,
                  :class => 'navbar-link'

    .container
      = render_breadcrumbs separator: ' / '
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
      = yield

    %footer{:role => "contentinfo"}
      .container
        .row
          .col-sm-4
            %h4 Über uns
            %p
              Das Team hinter Book and Read besteht aus Martin Görick, Paul
              Kunze, Dennis Hägler und Philip Drozd.
            %p
              Wir wollen den Austausch von Fachbüchern fördern und dafür
              eine Plattform für alle bereitstellen.
            %p
              © 2015 Book and Read
          .col-sm-4
            %h4 Menü
            %nav
              %ul
                %li
                  = link_to 'Startseite', root_path
                %li
                  = link_to 'Verfügbare Bücher', available_books_path
                %li
                  = link_to 'Impressum', imprint_path
          .col-sm-4
            %h4 Kontakt
            %address
              %p
                Machonstraße 24
                %br
                12105 Berlin
              %p E-Mail: info@bookandread.com